# ui_skin/pages/2_🔮_sandbox.py

import os
import sys
import json
import streamlit as st
import pandas as pd
from pathlib import Path

# Absolute project path resolution to handle multi-page layout shifts smoothly
root_dir = Path(__file__).resolve().parent.parent.parent
if str(root_dir) not in sys.path:
    sys.path.append(str(root_dir))

# Import our universal accounting master engine
from ui_skin.core_engine.double_entry_matrix import compile_three_way_forecast

# Verify user security clearance before rendering ledger parameters
if not st.session_state.get("authenticated", False):
    st.error("🔒 Access Denied: Unauthorized Endpoints Locked")
    st.info("This environment is shielded by an enterprise security framework. You must log in via the main portal to open this workspace.")
    st.stop()

st.title("🔮 Multi-Variant Scenario Sandbox")
st.caption("Systems-Thinking Scratchpad • Test Asset Deviations & High-Impact Projections")
st.markdown("---")

# Verify an active project configuration baseline file exists to model against
selected_project = st.session_state.get("selected_project", "")
if not selected_project:
    st.warning("⚠️ No Active Project Context Detected. Please load a baseline configuration state in the Ingestion Suite before accessing this sandbox.")
    st.stop()

st.sidebar.success(f"📁 Modelling Sandbox Matrix for: `{selected_project}`")

# --- ⚙️ UNIVERSAL SCENARIO STRESS CONTROLS ---
st.subheader("🎛️ Scenario Stress Testing Controls")
st.markdown("Adjust these parameters to scale values up or down across your active project baseline matrices:")

col1, col2 = st.columns(2)
with col1:
    sandbox_volume_delta = st.slider("Revenue Volume Delta / Growth Spike (%)", min_value=-50, max_value=100, value=0, step=5)
    vol_multiplier = 1.0 + (sandbox_volume_delta / 100.0)
with col2:
    sandbox_opex_delta = st.slider("Operational Overhead Cost Escalation (%)", min_value=-30, max_value=100, value=0, step=5)
    opex_multiplier = 1.0 + (sandbox_opex_delta / 100.0)

st.markdown("---")

# Define execution and presentation paths
base_json_path = os.path.join("saved_projects", f"{selected_project}.json")
sandbox_json_path = os.path.join("saved_projects", f"SANDBOX_VARIANT_{selected_project}.json")

# --- ⚙️ MASTER TRANSACTION SCENARIO COMPILER ---
with st.spinner("Executing dynamic double-entry scenario run..."):
    try:
        # Load the clean baseline tracking queues from disk
        if not os.path.exists(base_json_path):
            st.error("Baseline project parameter file missing from disk storage target.")
            st.stop()
            
        with open(base_json_path, "r") as bf:
            payload = json.load(bf)
            
        # Initialize variant queues
        variant_payload = {
            "sales": [],
            "opex": [],
            "capital": payload.get("capital", []) # Capital asset infusions remain locked to baseline defaults
        }
        
        # Apply scaling delta multipliers uniformly across the raw rows
        for item in payload.get("sales", []):
            modified_item = item.copy()
            modified_item["amount"] = float(item.get("amount", 0.0)) * vol_multiplier
            variant_payload["sales"].append(modified_item)
            
        for item in payload.get("opex", []):
            modified_item = item.copy()
            modified_item["amount"] = float(item.get("amount", 0.0)) * opex_multiplier
            variant_payload["opex"].append(modified_item)
            
        # Serialize the dynamically altered data state to a temporary sandbox run file
        with open(sandbox_json_path, "w") as sf:
            json.dump(variant_payload, sf, indent=4)
            
        # Re-run our master trial balance routine on the variant file to update statement caches
        compile_three_way_forecast(sandbox_json_path)
        
        # Load the updated outputs generated by the double-entry calculation block
        pl_cache = "STRATA_Forecast_Ledger_Group.xlsx - Profit & Loss.csv"
        cf_cache = "STRATA_Forecast_Ledger_Group.xlsx - Cash Flow Ledger.csv"
        
        if os.path.exists(pl_cache) and os.path.exists(cf_cache):
            pl_df = pd.read_csv(pl_cache, index_col=0)
            cf_df = pd.read_csv(cf_cache, index_col=0)
            
            # Reconstruct the tracking layout view for the sandbox page
            df_sandbox_display = pd.DataFrame({
                "Variant Revenue (£)": pl_df["Revenue (£)"],
                "Variant OpEx (£)": pl_df["Opex (£)"],
                "Net Operational Profit (£)": pl_df["EBIT (£)"],
                "Projected Cash Position (£)": cf_df["Cash Reserves (£)"]
            }, index=pl_df.index).T
            
            st.subheader("📊 Visualized Run-Rate Impact Matrix (60-Month View)")
            st.dataframe(df_sandbox_display.style.format("{:,.2f}"), use_container_width=True)
            
            # Render a quick visualization curve of the modified cash runway
            st.markdown("#### 📈 Variant Cash Reserves Trajectory")
            st.line_chart(cf_df["Cash Reserves (£)"], use_container_width=True)
            st.success("🔒 Double-Entry Sandbox Verification Check: Trial balance reconciled (Debits = Credits)")
            
        else:
            st.error("Error: Calculation outputs could not be retrieved from core repository caches.")
            
    except Exception as e:
        st.error(f"Sandbox Variant Systemic Execution Error: {str(e)}")