# ui_skin/pages/4_🛡️_compliance.py
import sys
from pathlib import Path

# --- CRITICAL PATH RESOLUTION ---
root_dir = Path(__file__).resolve().parent.parent.parent
if str(root_dir) not in sys.path:
    sys.path.append(str(root_dir))

import streamlit as st
import pandas as pd
import numpy as np

# Cloud Container Path Resolution Fix - Point directly to the central calculation engine
from ui_skin.core_engine.master_model import generate_integrated_3way_forecast

st.set_page_config(layout="wide", page_title="Compliance & Payroll Deck")

st.title("🛡️ Corporate Compliance & Payroll Auditor")
st.caption("Statutory Tax Schedules, PAYE/NI Obligations, and Auto-Enrolment Pension Auditing")
st.markdown("---")

# --- 1. SESSION STATE VERIFICATION ---
if "baseline_inputs" not in st.session_state:
    st.warning("⚠️ **Upstream Data Missing:** Active session data not detected. Please initialize your parameters on the Ingestion page first.")
    st.stop()

# Clone inputs package with fallback safety for legacy key variants
inputs_package = st.session_state["baseline_inputs"].copy()

# Guard against key mismatches by normalizing expectations
if "base_gross_wages" not in inputs_package and "base_monthly_gross_wages" in inputs_package:
    inputs_package["base_gross_wages"] = inputs_package["base_monthly_gross_wages"]

# --- 2. EXECUTE UNIFIED MODEL ENGINE ---
with st.spinner("Analyzing compliance tracking metrics..."):
    # Execute our single source of truth forecast matrix matching your WinForecast curves
    engine_output = generate_integrated_3way_forecast(
        inputs=inputs_package,
        overrides={}
    )

# Timeline columns configuration
timeline_columns = [f"Month {i}" for i in range(1, 61)]

# --- 3. COMPLIANCE METRICS CALCULATION ---
gross_wages_monthly = float(inputs_package.get("base_monthly_gross_wages", 12000.0))
directors_salaries_monthly = float(inputs_package.get("directors_salaries_monthly", 5150.0))
pension_opt_out = inputs_package.get("pension_opt_out", False)

# Statutory UK Payroll Approximations (Employer NI @ 13.8% above threshold, Pension @ 3%)
employer_ni_monthly = max(0.0, (gross_wages_monthly - 758.0) * 0.138) if gross_wages_monthly > 758.0 else 0.0
pension_contribution_monthly = 0.0 if pension_opt_out else (gross_wages_monthly * 0.03)

# Derive the 9-month lagged physical tax cash paid timeline to align with tax_engine rules
tax_expense_timeline = engine_output["Tax Expense (£)"].values
tax_cash_paid_timeline = np.zeros(60)
for m in range(60):
    if m >= 9:
        tax_cash_paid_timeline[m] = tax_expense_timeline[m - 9]

# Build a synchronized audit schedule dataframe mapping directly to engine variables
compliance_data = {
    "Gross Staff Salaries (£)": np.full(60, gross_wages_monthly),
    "Directors Remuneration (£)": np.full(60, directors_salaries_monthly),
    "Estimated Employer National Insurance (NI) (£)": np.full(60, employer_ni_monthly),
    "Auto-Enrolment Pension Contributions (£)": np.full(60, pension_contribution_monthly),
    "**Total Monthly Payroll Burden (£)**": np.full(60, gross_wages_monthly + directors_salaries_monthly + employer_ni_monthly + pension_contribution_monthly),
    "Accrued Corporation Tax Liability (£)": engine_output["Tax Liability BS (£)"].values,
    "Actual Corporation Tax Cash Paid (£)": tax_cash_paid_timeline
}

compliance_df = pd.DataFrame(compliance_data, index=timeline_columns).T

# --- 4. DISPLAY AUDIT BLOCKS ---
col_stat1, col_stat2, col_stat3 = st.columns(3)
with col_stat1:
    st.metric("Auto-Enrolment Status", "COMPLIANT ✅" if not pension_opt_out else "OPTED OUT ⛔")
with col_stat2:
    st.metric("Monthly Payroll Tax Obligation", f"£{employer_ni_monthly:,.2f}")
with col_stat3:
    st.metric("Peak Corporate Tax Liability", f"£{engine_output['Tax Liability BS (£)'].max():,.2f}")

st.markdown("### **Statutory Compliance & Payroll Audit Ledger**")
st.caption("Verifies real-time tax provisions and workforce pension costs generated by the master three-way matrix engine.")
st.dataframe(compliance_df.style.format("£{:,.2f}"), use_container_width=True)