# core_engine/reconciliation.py
import pandas as pd
import numpy as np

def run_variance_audit(engine_outputs, legacy_reports):
    """
    Executes a line-by-line mathematical comparison between the new 
    Python 3-way engine outputs and the legacy WinForecast benchmarks.
    
    Parameters:
        engine_outputs (dict): Arrays generated by master_model.py
        legacy_reports (dict): Hardcoded baseline arrays from legacy files
        
    Returns:
        pd.DataFrame: A comprehensive variance matrix highlighting discrepancies.
    """
    audit_records = []
    
    # Iterate through core matching lines across the financial statements
    target_lines = ["Revenue", "COGS", "Net Profit", "Cash at Bank", "Total Debtors", "Total Liabilities"]
    
    for line in target_lines:
        if line in engine_outputs and line in legacy_reports:
            actual = np.array(engine_outputs[line][:12]) # Audit first 12 months first
            benchmark = np.array(legacy_reports[line][:12])
            
            # Compute absolute and percentage variances
            variance = actual - benchmark
            
            for month_idx in range(12):
                v_amt = variance[month_idx]
                status = "VERIFIED" if abs(v_amt) < 2.0 else "VARIANCE DETECTED"
                
                # Diagnostics categorization
                diagnostic = "Pass"
                if status == "VARIANCE DETECTED":
                    if abs(v_amt) <= abs(actual[month_idx] * 0.001):
                        diagnostic = "Rounding Tolerable"
                    else:
                        diagnostic = "Review Timing Logics"
                
                audit_records.append({
                    "Line Item": line,
                    "Month": f"Month {month_idx + 1}",
                    "STRATA Engine (£)": actual[month_idx],
                    "WinForecast (£)": benchmark[month_idx],
                    "Variance (£)": v_amt,
                    "Audit Status": status,
                    "Diagnostic Note": diagnostic
                })
                
    return pd.DataFrame(audit_records)