# .streamlit/secrets.toml

[postgres]
url = "postgresql://neondb_owner:npg_z4vM5IsolfTC@ep-frosty-morning-abslxsb3-pooler.eu-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
[gemini]
api_key = "AIzaSyDHTHPjoofO2Saz8IdKS-9WwT1_ca8ePSk"